### ISSUE TITLE
send inv msg to fetch missing tx

### ISSUE THREAD

**Issue by whitefen** [copernet/copernicus#207]
**Describe the bug**
send inv msg to fetch missing tx

**To Reproduce**
function fetchMissingTx in syncmanager.go

**Expected behavior**
send getdata msg

**Screenshots**

**Desktop (please complete the following information):**
 - OS:linux

**Comment by whunmr** [comment]
fixing this one

**Comment by whunmr** [comment]
@whitefen please help to review this fix, thanks

https://github.com/whunmr/copernicus/commit/fffb5ed337e6d3b126bb1ab48b669bfdc938d0ba

**Comment by whunmr** [comment]
@whitefen reviewed. will close now.
