### ISSUE TITLE
QuickStart issue

### ISSUE THREAD

**Issue by wolfstudy** [copernet/copernicus#219]
## OS
mac

## occurred problem
when I execute `./autoinstall.sh`, the following error occurred:

```
./autoinstall.sh: line 3: autoreconf: command not found
```

autoinstall.sh file：

```
  1 #!/bin/sh
  2 set -e
  3 autoreconf -if --warnings=all
  4 ./configure --enable-module-ecdh --enable-module-recovery --enable-experimental
  5 make -j8
  6 make install
```
## identify the problem

we don't have the dependencies we need to install

## solution

```
brew install automake berkeley-db libtool boost --c++11 miniupnpc openssl pkg-config protobuf --c++11 libevent
```

**Comment by whunmr** [comment]
fixed in commit https://github.com/copernet/secp256k1/commit/c609e9491574260f161512768c147771496d29ce
