### ISSUE TITLE
Rpc respond 503 Too busy

### ISSUE THREAD

**Issue by FMLS** [copernet/copernicus#223]
**Describe the bug**
coperctl --notls -s xxx.xxx.xxx.xxx:xxx help
503 Too busy

but there is just one connection to copernicus, and there is none log with that problem

**Comment by whunmr** [comment]
hi  @FMLS , do you know the steps to reproduce this issue?

**Comment by whitefen** [comment]
Check the config 'RPC.RPCMaxClients', is it  set to 0?

**Comment by FMLS** [comment]
> hi @FMLS , do you know the steps to reproduce this issue?

no, it's a accidental bug

**Comment by FMLS** [comment]
> Check the config 'RPC.RPCMaxClients', is it set to 0?

no，value of it is 1000 by default

**Comment by whunmr** [comment]
reproduced in testnet by @FMLS  and fixed by @whitefen 

check details in:
https://github.com/copernet/copernicus/pull/232
