### ISSUE TITLE
Unable to checkout golang.org/x/crypto

### ISSUE THREAD

**Issue by jjz** [copernet/copernicus#82]
[WARN]  Unable to checkout golang.org/x/crypto
[ERROR] Update failed for golang.org/x/crypto: Cannot detect VCS
[ERROR] Failed to do initial checkout of config: Cannot detect VCS

**Comment by detailyang** [comment]
Hello.
It almost is influenced by GFW, See [https://sourcegraph.com/github.com/Masterminds/glide@3e13fd16ed5b0808ba0fb2e4bd98eb325ccde0a1/-/blob/util/util.go#L144](https://sourcegraph.com/github.com/Masterminds/glide@3e13fd16ed5b0808ba0fb2e4bd98eb325ccde0a1/-/blob/util/util.go#L144).

using glide mirror ` glide mirror set https://golang.org/x/crypto https://github.com/golang/crypto --vcs git` is a workaround. But enable proxy via HTTP proxy in CLI will be better as the following:

````bash
    export HTTPS_PROXY=http://127.0.0.1:1087
    export HTTP_PROXY=http://127.0.0.1:1087
````
